services:
  db:
    image: postgres:latest
    volumes:
      - db_data:/data/db
    restart: always
    ports:
     - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db

  redis:
    image: redis:latest
    restart: always
    command: >
      --requirepass password
    ports:
     - "6379:6379"

volumes:
  db_data: